#!/bin/bash

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/common.sh

destination=$1
payload=$(mktemp $TMPDIR/vault-resource-request.XXXXXX)
cat > $payload <&0

url=$(jq -r '.source.uri // "https://vault.service.consul:8200"' < $payload)
skip_verify=$(jq -r '.source.tls_skip_verify // ""' < $payload)
role=$(jq -r '.source.role // "concourse"' < $payload)
nonce=$(jq -r '.source.nonce // "vault-concourse-nonce"' < $payload)
paths=($(jq -r '.params.paths // [] | .[]' < $payload))

echo "INFO: Reading secrets from: ${paths[*]}"

export VAULT_ADDR=${url}
if [ ! -z "${skip_verify}" ]; then
    echo "WARN: Disabling TLS verification for Vault"
    export VAULT_SKIP_VERIFY=1
fi

login ${role} ${nonce}

for path in "${paths[@]}"; do
    mkdir -p ${destination}/$(dirname ${path})
    get_secret ${path} > ${destination}/${path}.json
done

version="{\"date\": \"$(date +%s)\"}"
jq -n "{
  version: ${version}
}" >&3
