#!/bin/bash

set -e

source $(dirname $0)/common.sh

destination=$1
payload=$(mktemp $TMPDIR/vault-resource-request.XXXXXX)
cat > $payload <&0

url=$(jq -r '.source.url // "https://vault.service.consul:8200"' < $payload)
role=$(jq -r '.source.role // "concourse"' < $payload)
nonce=$(jq -r '.source.nonce // "vault-concourse-nonce"' < $payload)
paths=($(jq -r '.params.paths // [] | .[]' < $payload))
version_path=$(jq -r 'source.version // "version"' < $payload)

token=$(login "${url}" "${role}" "${nonce}")

for path in "${paths[@]}"; do
    mkdir -p ${destination}/$(dirname ${path})
    get_secret "${url}" "${token}" "${path}" > ${destination}/${path}.json
done

version=$(get_secret "${url}" "${token}" "${version_path}" | jq -r '.version')
jq -n "{
  version: ${version}
}"
